[system]
# Name
system_name = "50BuOH-CG"
# Files
topology_file_path = "configs/butanol-data/50BuOH/first_frame.pdb"
trajectory_file_path = "configs/butanol-data/50BuOH/50Bu200step.xtc"
rdf_file_path = "configs/butanol-data/50BuOH/rdf50bu.txt"
# Simulation
temperature = 300          # Temperature [K]
max_displacement = 8.50       # Maximum atomic displacement [Å]
target_acceptance_ratio = 0.5 # Monte Carlo acceptance ratio target
concentration = 50.0          # System concentration
