[system]
# Name
system_name = "90CH3OH-CG"
# Files
topology_file_path = "configs/methanol-data/90CH3OH/90CH3OH-CG.pdb"
trajectory_file_path = "configs/methanol-data/90CH3OH/90CH3OH-CG-200.xtc"
rdf_file_path = "configs/methanol-data/90CH3OH/90CH3OH-CG.rdf"
# Simulation
temperature = 298.15          # Temperature [K]
max_displacement = 1.35       # Maximum atomic displacement [Å]
target_acceptance_ratio = 0.5 # Monte Carlo acceptance ratio target
concentration = 90.0          # System concentration
