[system]
# Name
system_name = "20CH3OH-CG"
# Files
topology_file_path = "configs/methanol-data/20CH3OH/20CH3OH-CG.pdb"
trajectory_file_path = "configs/methanol-data/20CH3OH/20CH3OH-CG-200.xtc"
rdf_file_path = "configs/methanol-data/20CH3OH/20CH3OH-CG.rdf"
# Simulation
temperature = 298.15          # Temperature [K]
max_displacement = 3.75       # Maximum atomic displacement [Å]
target_acceptance_ratio = 0.5 # Monte Carlo acceptance ratio target
concentration = 20.0          # System concentration
