[system]
# Name
system_name = "60BuOH-CG"
# Files
topology_file_path = "configs/butanol-data/60BuOH/first_frame.pdb"
trajectory_file_path = "configs/butanol-data/60BuOH/60Bu200step.xtc"
rdf_file_path = "configs/butanol-data/60BuOH/rdf60bu.txt"
# Simulation
temperature = 300             # Temperature [K]
max_displacement = 8.50       # Maximum atomic displacement [Å]
target_acceptance_ratio = 0.5 # Monte Carlo acceptance ratio target
concentration = 60.0          # System concentration
