[system]
# Name
system_name = "80BuOH-CG"
# Files
topology_file_path = "configs/butanol-data/80BuOH/first_frame.pdb"
trajectory_file_path = "configs/butanol-data/80BuOH/80Bu200step.xtc"
rdf_file_path = "configs/butanol-data/80BuOH/rdf80bu.txt"
# Simulation
temperature = 300          # Temperature [K]
max_displacement = 8.50       # Maximum atomic displacement [Å]
target_acceptance_ratio = 0.5 # Monte Carlo acceptance ratio target
concentration = 80.0          # System concentration
