[system]
# Name
system_name = "30BuOH-CG"
# Files
topology_file_path = "configs/butanol-data/30BuOH/first_frame.pdb"
trajectory_file_path = "configs/butanol-data/30BuOH/30Bu200step.xtc"
rdf_file_path = "configs/butanol-data/30BuOH/rdf30bu.txt"
# Simulation
temperature = 300             # Temperature [K]
max_displacement = 8.50       # Maximum atomic displacement [Å]
target_acceptance_ratio = 0.5 # Monte Carlo acceptance ratio target
concentration = 30.0          # System concentration
