[system]
# Name
system_name = "20BuOH-CG"
# Files
topology_file_path = "configs/butanol-data/20BuOH/first_frame.pdb"
trajectory_file_path = "configs/butanol-data/20BuOH/20Bu200step.xtc"
rdf_file_path = "configs/butanol-data/20BuOH/rdf20bu.txt"
# Simulation
temperature = 300          # Temperature [K]
max_displacement = 8.50       # Maximum atomic displacement [Å]
target_acceptance_ratio = 0.5 # Monte Carlo acceptance ratio target
concentration = 20.0          # System concentration
