[system]
# Name
system_name = "50CH3OH-CG"
# Files
topology_file_path = "configs/methanol-data/50CH3OH/50CH3OH-CG.pdb"
trajectory_file_path = "configs/methanol-data/50CH3OH/50CH3OH-CG-200.xtc"
rdf_file_path = "configs/methanol-data/50CH3OH/50CH3OH-CG.rdf"
# Simulation
temperature = 298.15          # Temperature [K]
max_displacement = 2.00       # Maximum atomic displacement [Å]
target_acceptance_ratio = 0.5 # Monte Carlo acceptance ratio target
concentration = 50.0          # System concentration
